export const Filter = 'filter'
export const Output = 'output'
export const MainProcess = 'MainProcess'
export const SharedProcess = 'SharedProcess'
export const Clear = 'Clear'
export const Settings = 'Settings'
export const ScrollLock = 'ScrollLock'
